"""init

Revision ID: f0dbf44b2637
Revises: 
Create Date: 2025-12-21 10:07:20.659020

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f0dbf44b2637'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('pdf', sa.String(), nullable=True),
    sa.Column('audio', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('days_of_study', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('reg_num', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('father_name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('family_name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_teacher', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_male', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reg_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_reg_num'), 'user', ['reg_num'], unique=True)
    op.create_table('lesson',
    sa.Column('book_part_pdf', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('book_part_audio', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lesson_audio', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('explanation_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'order', name='uq_lesson_book_order')
    )
    op.create_index(op.f('ix_lesson_order'), 'lesson', ['order'], unique=False)
    op.create_table('phase',
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'order', name='uq_phase_program_order')
    )
    op.create_index(op.f('ix_phase_order'), 'phase', ['order'], unique=False)
    op.create_table('session',
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('program_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam',
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phase_book',
    sa.Column('phase_id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phase_id'], ['phase.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('phase_id', 'book_id'),
    sa.UniqueConstraint('phase_id', 'order', name='uq_phase_book_phase_order')
    )
    op.create_index(op.f('ix_phase_book_order'), 'phase_book', ['order'], unique=False)
    op.create_table('question',
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_options', sa.JSON(), nullable=True),
    sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_event',
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('num_days', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('is_break', sa.Boolean(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_event_is_break'), 'session_event', ['is_break'], unique=False)
    op.create_table('user_session_student',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'session_id')
    )
    op.create_table('user_session_teacher',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'session_id')
    )
    op.create_table('exam_attempt',
    sa.Column('observation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('attempt_date', sa.Date(), nullable=False),
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('examiner_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['examiner_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_attempt')
    op.drop_table('user_session_teacher')
    op.drop_table('user_session_student')
    op.drop_index(op.f('ix_session_event_is_break'), table_name='session_event')
    op.drop_table('session_event')
    op.drop_table('question')
    op.drop_index(op.f('ix_phase_book_order'), table_name='phase_book')
    op.drop_table('phase_book')
    op.drop_table('exam')
    op.drop_table('session')
    op.drop_index(op.f('ix_phase_order'), table_name='phase')
    op.drop_table('phase')
    op.drop_index(op.f('ix_lesson_order'), table_name='lesson')
    op.drop_table('lesson')
    op.drop_index(op.f('ix_user_reg_num'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('program')
    op.drop_table('book')
    # ### end Alembic commands ###
