"""Add unique constaint on phase-book association

Revision ID: 0aad593d8456
Revises: f0dbf44b2637
Create Date: 2026-02-01 20:58:21.631047

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0aad593d8456'
down_revision = 'f0dbf44b2637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_phase_book_phase_book', 'phase_book', ['phase_id', 'book_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_phase_book_phase_book', 'phase_book', type_='unique')
    # ### end Alembic commands ###
