// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const BookCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            title: 'Title'
        },
        pdf: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pdf'
        },
        audio: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Audio'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'BookCreate'
} as const;

export const BookPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            title: 'Title'
        },
        pdf: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pdf'
        },
        audio: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Audio'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['title', 'id'],
    title: 'BookPublic'
} as const;

export const BookUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        pdf: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pdf'
        },
        audio: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Audio'
        }
    },
    type: 'object',
    title: 'BookUpdate'
} as const;

export const BooksPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/BookPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'BooksPublic'
} as const;

export const ExamAttemptCreateSchema = {
    properties: {
        observation: {
            type: 'string',
            title: 'Observation'
        },
        passed: {
            type: 'boolean',
            title: 'Passed'
        },
        exam_id: {
            type: 'string',
            format: 'uuid',
            title: 'Exam Id'
        },
        student_id: {
            type: 'string',
            format: 'uuid',
            title: 'Student Id'
        },
        examiner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Examiner Id'
        }
    },
    type: 'object',
    required: ['observation', 'passed', 'exam_id', 'student_id', 'examiner_id'],
    title: 'ExamAttemptCreate'
} as const;

export const ExamAttemptPublicSchema = {
    properties: {
        observation: {
            type: 'string',
            title: 'Observation'
        },
        passed: {
            type: 'boolean',
            title: 'Passed'
        },
        attempt_date: {
            type: 'string',
            format: 'date',
            title: 'Attempt Date'
        },
        exam_id: {
            type: 'string',
            format: 'uuid',
            title: 'Exam Id'
        },
        student_id: {
            type: 'string',
            format: 'uuid',
            title: 'Student Id'
        },
        examiner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Examiner Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['observation', 'passed', 'exam_id', 'student_id', 'examiner_id', 'id'],
    title: 'ExamAttemptPublic'
} as const;

export const ExamAttemptUpdateSchema = {
    properties: {
        observation: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Observation'
        },
        passed: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Passed'
        }
    },
    type: 'object',
    title: 'ExamAttemptUpdate'
} as const;

export const ExamAttemptsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ExamAttemptPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ExamAttemptsPublic'
} as const;

export const ExamCreateSchema = {
    properties: {
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        deadline: {
            type: 'string',
            format: 'date',
            title: 'Deadline'
        },
        max_attempts: {
            type: 'integer',
            minimum: 1,
            title: 'Max Attempts',
            default: 1
        },
        book_id: {
            type: 'string',
            format: 'uuid',
            title: 'Book Id'
        },
        session_id: {
            type: 'string',
            format: 'uuid',
            title: 'Session Id'
        }
    },
    type: 'object',
    required: ['start_date', 'deadline', 'book_id', 'session_id'],
    title: 'ExamCreate'
} as const;

export const ExamPublicSchema = {
    properties: {
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        deadline: {
            type: 'string',
            format: 'date',
            title: 'Deadline'
        },
        max_attempts: {
            type: 'integer',
            minimum: 1,
            title: 'Max Attempts',
            default: 1
        },
        book_id: {
            type: 'string',
            format: 'uuid',
            title: 'Book Id'
        },
        session_id: {
            type: 'string',
            format: 'uuid',
            title: 'Session Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['start_date', 'deadline', 'book_id', 'session_id', 'id'],
    title: 'ExamPublic'
} as const;

export const ExamUpdateSchema = {
    properties: {
        start_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Date'
        },
        deadline: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deadline'
        },
        max_attempts: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Attempts'
        }
    },
    type: 'object',
    title: 'ExamUpdate'
} as const;

export const ExamsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ExamPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ExamsPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const LessonCreateSchema = {
    properties: {
        book_part_pdf: {
            type: 'string',
            title: 'Book Part Pdf'
        },
        book_part_audio: {
            type: 'string',
            title: 'Book Part Audio'
        },
        lesson_audio: {
            type: 'string',
            title: 'Lesson Audio'
        },
        explanation_notes: {
            type: 'string',
            title: 'Explanation Notes'
        },
        order: {
            type: 'integer',
            minimum: 0,
            title: 'Order'
        },
        book_id: {
            type: 'string',
            format: 'uuid',
            title: 'Book Id'
        }
    },
    type: 'object',
    required: ['book_part_pdf', 'book_part_audio', 'lesson_audio', 'explanation_notes', 'order', 'book_id'],
    title: 'LessonCreate'
} as const;

export const LessonPublicSchema = {
    properties: {
        book_part_pdf: {
            type: 'string',
            title: 'Book Part Pdf'
        },
        book_part_audio: {
            type: 'string',
            title: 'Book Part Audio'
        },
        lesson_audio: {
            type: 'string',
            title: 'Lesson Audio'
        },
        explanation_notes: {
            type: 'string',
            title: 'Explanation Notes'
        },
        order: {
            type: 'integer',
            minimum: 0,
            title: 'Order'
        },
        book_id: {
            type: 'string',
            format: 'uuid',
            title: 'Book Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['book_part_pdf', 'book_part_audio', 'lesson_audio', 'explanation_notes', 'order', 'book_id', 'id'],
    title: 'LessonPublic'
} as const;

export const LessonUpdateSchema = {
    properties: {
        book_part_pdf: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Book Part Pdf'
        },
        book_part_audio: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Book Part Audio'
        },
        lesson_audio: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lesson Audio'
        },
        explanation_notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Explanation Notes'
        }
    },
    type: 'object',
    title: 'LessonUpdate'
} as const;

export const LessonsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/LessonPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'LessonsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PhaseCreateSchema = {
    properties: {
        order: {
            type: 'integer',
            minimum: 0,
            title: 'Order'
        },
        program_id: {
            type: 'string',
            format: 'uuid',
            title: 'Program Id'
        }
    },
    type: 'object',
    required: ['order', 'program_id'],
    title: 'PhaseCreate'
} as const;

export const PhasePublicSchema = {
    properties: {
        order: {
            type: 'integer',
            minimum: 0,
            title: 'Order'
        },
        program_id: {
            type: 'string',
            format: 'uuid',
            title: 'Program Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['order', 'program_id', 'id'],
    title: 'PhasePublic'
} as const;

export const PhaseUpdateSchema = {
    properties: {
        order: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Order'
        }
    },
    type: 'object',
    title: 'PhaseUpdate'
} as const;

export const PhasesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/PhasePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'PhasesPublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        first_name: {
            type: 'string',
            title: 'First Name'
        },
        father_name: {
            type: 'string',
            title: 'Father Name'
        },
        family_name: {
            type: 'string',
            title: 'Family Name'
        },
        is_male: {
            type: 'boolean',
            title: 'Is Male'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'first_name', 'father_name', 'family_name', 'is_male'],
    title: 'PrivateUserCreate'
} as const;

export const ProgramCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            title: 'Title'
        },
        days_of_study: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Days Of Study'
        }
    },
    type: 'object',
    required: ['title', 'days_of_study'],
    title: 'ProgramCreate'
} as const;

export const ProgramPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            title: 'Title'
        },
        days_of_study: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Days Of Study'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['title', 'days_of_study', 'id'],
    title: 'ProgramPublic'
} as const;

export const ProgramSessionCreateSchema = {
    properties: {
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        program_id: {
            type: 'string',
            format: 'uuid',
            title: 'Program Id'
        }
    },
    type: 'object',
    required: ['start_date', 'program_id'],
    title: 'ProgramSessionCreate'
} as const;

export const ProgramSessionPublicSchema = {
    properties: {
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        program_id: {
            type: 'string',
            format: 'uuid',
            title: 'Program Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['start_date', 'program_id', 'id'],
    title: 'ProgramSessionPublic'
} as const;

export const ProgramSessionUpdateSchema = {
    properties: {
        start_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Date'
        }
    },
    type: 'object',
    title: 'ProgramSessionUpdate'
} as const;

export const ProgramSessionsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProgramSessionPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ProgramSessionsPublic'
} as const;

export const ProgramUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        days_of_study: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Days Of Study'
        }
    },
    type: 'object',
    title: 'ProgramUpdate'
} as const;

export const ProgramsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProgramPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ProgramsPublic'
} as const;

export const QuestionCreateSchema = {
    properties: {
        question: {
            type: 'string',
            title: 'Question'
        },
        options: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Options'
        },
        correct_options: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Correct Options'
        },
        explanation: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Explanation'
        },
        lesson_id: {
            type: 'string',
            format: 'uuid',
            title: 'Lesson Id'
        }
    },
    type: 'object',
    required: ['question', 'options', 'correct_options', 'lesson_id'],
    title: 'QuestionCreate'
} as const;

export const QuestionPublicSchema = {
    properties: {
        question: {
            type: 'string',
            title: 'Question'
        },
        options: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Options'
        },
        correct_options: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Correct Options'
        },
        explanation: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Explanation'
        },
        lesson_id: {
            type: 'string',
            format: 'uuid',
            title: 'Lesson Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['question', 'options', 'correct_options', 'lesson_id', 'id'],
    title: 'QuestionPublic'
} as const;

export const QuestionUpdateSchema = {
    properties: {
        question: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Question'
        },
        options: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Options'
        },
        correct_options: {
            anyOf: [
                {
                    items: {
                        type: 'integer'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Correct Options'
        },
        explanation: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Explanation'
        }
    },
    type: 'object',
    title: 'QuestionUpdate'
} as const;

export const QuestionsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/QuestionPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'QuestionsPublic'
} as const;

export const SessionEventCreateSchema = {
    properties: {
        event_date: {
            type: 'string',
            format: 'date',
            title: 'Event Date'
        },
        num_days: {
            type: 'integer',
            minimum: 1,
            title: 'Num Days',
            default: 1
        },
        session_id: {
            type: 'string',
            format: 'uuid',
            title: 'Session Id'
        },
        is_break: {
            type: 'boolean',
            title: 'Is Break',
            default: false
        },
        lesson_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lesson Id'
        }
    },
    type: 'object',
    required: ['event_date', 'session_id'],
    title: 'SessionEventCreate'
} as const;

export const SessionEventPublicSchema = {
    properties: {
        event_date: {
            type: 'string',
            format: 'date',
            title: 'Event Date'
        },
        num_days: {
            type: 'integer',
            minimum: 1,
            title: 'Num Days',
            default: 1
        },
        session_id: {
            type: 'string',
            format: 'uuid',
            title: 'Session Id'
        },
        is_break: {
            type: 'boolean',
            title: 'Is Break',
            default: false
        },
        lesson_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lesson Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['event_date', 'session_id', 'id'],
    title: 'SessionEventPublic'
} as const;

export const SessionEventsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/SessionEventPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'SessionEventsPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        reg_num: {
            type: 'string',
            format: 'uuid',
            title: 'Reg Num'
        },
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        first_name: {
            type: 'string',
            maxLength: 30,
            title: 'First Name'
        },
        father_name: {
            type: 'string',
            maxLength: 30,
            title: 'Father Name'
        },
        family_name: {
            type: 'string',
            maxLength: 30,
            title: 'Family Name'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_admin: {
            type: 'boolean',
            title: 'Is Admin',
            default: false
        },
        is_teacher: {
            type: 'boolean',
            title: 'Is Teacher',
            default: false
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        is_male: {
            type: 'boolean',
            title: 'Is Male'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        reg_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reg Date'
        }
    },
    type: 'object',
    required: ['email', 'first_name', 'father_name', 'family_name', 'is_male', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        reg_num: {
            type: 'string',
            format: 'uuid',
            title: 'Reg Num'
        },
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        first_name: {
            type: 'string',
            maxLength: 30,
            title: 'First Name'
        },
        father_name: {
            type: 'string',
            maxLength: 30,
            title: 'Father Name'
        },
        family_name: {
            type: 'string',
            maxLength: 30,
            title: 'Family Name'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_admin: {
            type: 'boolean',
            title: 'Is Admin',
            default: false
        },
        is_teacher: {
            type: 'boolean',
            title: 'Is Teacher',
            default: false
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        is_male: {
            type: 'boolean',
            title: 'Is Male'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['email', 'first_name', 'father_name', 'family_name', 'is_male', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        first_name: {
            type: 'string',
            maxLength: 30,
            title: 'First Name'
        },
        father_name: {
            type: 'string',
            maxLength: 30,
            title: 'Father Name'
        },
        family_name: {
            type: 'string',
            maxLength: 30,
            title: 'Family Name'
        },
        is_male: {
            type: 'boolean',
            title: 'Is Male'
        }
    },
    type: 'object',
    required: ['email', 'password', 'first_name', 'father_name', 'family_name', 'is_male'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        },
        first_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 30
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        father_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 30
                },
                {
                    type: 'null'
                }
            ],
            title: 'Father Name'
        },
        family_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 30
                },
                {
                    type: 'null'
                }
            ],
            title: 'Family Name'
        },
        is_male: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Male'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        is_admin: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Admin'
        },
        is_teacher: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Teacher'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        first_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 30
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        father_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 30
                },
                {
                    type: 'null'
                }
            ],
            title: 'Father Name'
        },
        family_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 30
                },
                {
                    type: 'null'
                }
            ],
            title: 'Family Name'
        },
        is_male: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Male'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;