/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutWelcomeRouteImport } from './routes/_layout/welcome'
import { Route as LayoutSignupRouteImport } from './routes/_layout/signup'
import { Route as LayoutLoginRouteImport } from './routes/_layout/login'
import { Route as LayoutExampleRouteImport } from './routes/_layout/example'
import { Route as LayoutProgramsIndexRouteImport } from './routes/_layout/programs/index'
import { Route as LayoutProgramsProgramIdPhasesIndexRouteImport } from './routes/_layout/programs/$programId/phases/index'
import { Route as LayoutProgramsProgramIdPhasesPhaseIdBooksBookIdIndexRouteImport } from './routes/_layout/programs/$programId/phases/$phaseId/books/$bookId/index'
import { Route as LayoutProgramsProgramIdPhasesPhaseIdBooksBookIdCoursesCourseIdIndexRouteImport } from './routes/_layout/programs/$programId/phases/$phaseId/books/$bookId/courses/$courseId/index'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWelcomeRoute = LayoutWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSignupRoute = LayoutSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLoginRoute = LayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExampleRoute = LayoutExampleRouteImport.update({
  id: '/example',
  path: '/example',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProgramsIndexRoute = LayoutProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProgramsProgramIdPhasesIndexRoute =
  LayoutProgramsProgramIdPhasesIndexRouteImport.update({
    id: '/programs/$programId/phases/',
    path: '/programs/$programId/phases/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutProgramsProgramIdPhasesPhaseIdBooksBookIdIndexRoute =
  LayoutProgramsProgramIdPhasesPhaseIdBooksBookIdIndexRouteImport.update({
    id: '/programs/$programId/phases/$phaseId/books/$bookId/',
    path: '/programs/$programId/phases/$phaseId/books/$bookId/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutProgramsProgramIdPhasesPhaseIdBooksBookIdCoursesCourseIdIndexRoute =
  LayoutProgramsProgramIdPhasesPhaseIdBooksBookIdCoursesCourseIdIndexRouteImport.update(
    {
      id: '/programs/$programId/phases/$phaseId/books/$bookId/courses/$courseId/',
      path: '/programs/$programId/phases/$phaseId/books/$bookId/courses/$courseId/',
      getParentRoute: () => LayoutRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/example': typeof LayoutExampleRoute
  '/login': typeof LayoutLoginRoute
  '/signup': typeof LayoutSignupRoute
  '/welcome': typeof LayoutWelcomeRoute
  '/': typeof LayoutIndexRoute
  '/programs': typeof LayoutProgramsIndexRoute
  '/programs/$programId/phases': typeof LayoutProgramsProgramIdPhasesIndexRoute
  '/programs/$programId/phases/$phaseId/books/$bookId': typeof LayoutProgramsProgramIdPhasesPhaseIdBooksBookIdIndexRoute
  '/programs/$programId/phases/$phaseId/books/$bookId/courses/$courseId': typeof LayoutProgramsProgramIdPhasesPhaseIdBooksBookIdCoursesCourseIdIndexRoute
}
export interface FileRoutesByTo {
  '/example': typeof LayoutExampleRoute
  '/login': typeof LayoutLoginRoute
  '/signup': typeof LayoutSignupRoute
  '/welcome': typeof LayoutWelcomeRoute
  '/': typeof LayoutIndexRoute
  '/programs': typeof LayoutProgramsIndexRoute
  '/programs/$programId/phases': typeof LayoutProgramsProgramIdPhasesIndexRoute
  '/programs/$programId/phases/$phaseId/books/$bookId': typeof LayoutProgramsProgramIdPhasesPhaseIdBooksBookIdIndexRoute
  '/programs/$programId/phases/$phaseId/books/$bookId/courses/$courseId': typeof LayoutProgramsProgramIdPhasesPhaseIdBooksBookIdCoursesCourseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/example': typeof LayoutExampleRoute
  '/_layout/login': typeof LayoutLoginRoute
  '/_layout/signup': typeof LayoutSignupRoute
  '/_layout/welcome': typeof LayoutWelcomeRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/programs/': typeof LayoutProgramsIndexRoute
  '/_layout/programs/$programId/phases/': typeof LayoutProgramsProgramIdPhasesIndexRoute
  '/_layout/programs/$programId/phases/$phaseId/books/$bookId/': typeof LayoutProgramsProgramIdPhasesPhaseIdBooksBookIdIndexRoute
  '/_layout/programs/$programId/phases/$phaseId/books/$bookId/courses/$courseId/': typeof LayoutProgramsProgramIdPhasesPhaseIdBooksBookIdCoursesCourseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/example'
    | '/login'
    | '/signup'
    | '/welcome'
    | '/'
    | '/programs'
    | '/programs/$programId/phases'
    | '/programs/$programId/phases/$phaseId/books/$bookId'
    | '/programs/$programId/phases/$phaseId/books/$bookId/courses/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/example'
    | '/login'
    | '/signup'
    | '/welcome'
    | '/'
    | '/programs'
    | '/programs/$programId/phases'
    | '/programs/$programId/phases/$phaseId/books/$bookId'
    | '/programs/$programId/phases/$phaseId/books/$bookId/courses/$courseId'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/example'
    | '/_layout/login'
    | '/_layout/signup'
    | '/_layout/welcome'
    | '/_layout/'
    | '/_layout/programs/'
    | '/_layout/programs/$programId/phases/'
    | '/_layout/programs/$programId/phases/$phaseId/books/$bookId/'
    | '/_layout/programs/$programId/phases/$phaseId/books/$bookId/courses/$courseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/welcome': {
      id: '/_layout/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof LayoutWelcomeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/signup': {
      id: '/_layout/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof LayoutSignupRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/login': {
      id: '/_layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutLoginRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/example': {
      id: '/_layout/example'
      path: '/example'
      fullPath: '/example'
      preLoaderRoute: typeof LayoutExampleRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/programs/': {
      id: '/_layout/programs/'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof LayoutProgramsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/programs/$programId/phases/': {
      id: '/_layout/programs/$programId/phases/'
      path: '/programs/$programId/phases'
      fullPath: '/programs/$programId/phases'
      preLoaderRoute: typeof LayoutProgramsProgramIdPhasesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/programs/$programId/phases/$phaseId/books/$bookId/': {
      id: '/_layout/programs/$programId/phases/$phaseId/books/$bookId/'
      path: '/programs/$programId/phases/$phaseId/books/$bookId'
      fullPath: '/programs/$programId/phases/$phaseId/books/$bookId'
      preLoaderRoute: typeof LayoutProgramsProgramIdPhasesPhaseIdBooksBookIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/programs/$programId/phases/$phaseId/books/$bookId/courses/$courseId/': {
      id: '/_layout/programs/$programId/phases/$phaseId/books/$bookId/courses/$courseId/'
      path: '/programs/$programId/phases/$phaseId/books/$bookId/courses/$courseId'
      fullPath: '/programs/$programId/phases/$phaseId/books/$bookId/courses/$courseId'
      preLoaderRoute: typeof LayoutProgramsProgramIdPhasesPhaseIdBooksBookIdCoursesCourseIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutExampleRoute: typeof LayoutExampleRoute
  LayoutLoginRoute: typeof LayoutLoginRoute
  LayoutSignupRoute: typeof LayoutSignupRoute
  LayoutWelcomeRoute: typeof LayoutWelcomeRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutProgramsIndexRoute: typeof LayoutProgramsIndexRoute
  LayoutProgramsProgramIdPhasesIndexRoute: typeof LayoutProgramsProgramIdPhasesIndexRoute
  LayoutProgramsProgramIdPhasesPhaseIdBooksBookIdIndexRoute: typeof LayoutProgramsProgramIdPhasesPhaseIdBooksBookIdIndexRoute
  LayoutProgramsProgramIdPhasesPhaseIdBooksBookIdCoursesCourseIdIndexRoute: typeof LayoutProgramsProgramIdPhasesPhaseIdBooksBookIdCoursesCourseIdIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutExampleRoute: LayoutExampleRoute,
  LayoutLoginRoute: LayoutLoginRoute,
  LayoutSignupRoute: LayoutSignupRoute,
  LayoutWelcomeRoute: LayoutWelcomeRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutProgramsIndexRoute: LayoutProgramsIndexRoute,
  LayoutProgramsProgramIdPhasesIndexRoute:
    LayoutProgramsProgramIdPhasesIndexRoute,
  LayoutProgramsProgramIdPhasesPhaseIdBooksBookIdIndexRoute:
    LayoutProgramsProgramIdPhasesPhaseIdBooksBookIdIndexRoute,
  LayoutProgramsProgramIdPhasesPhaseIdBooksBookIdCoursesCourseIdIndexRoute:
    LayoutProgramsProgramIdPhasesPhaseIdBooksBookIdCoursesCourseIdIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
